system_configuration:
    groups:
        oroneo:
            title: 'synolia.oroneo.label'
            icon: icon-exchange
        oroneo_global_config:
            title: 'synolia.oroneo.configuration_page.global_configuration.title'
        oroneo_mapping_config:
            title: 'synolia.oroneo.configuration_page.mapping.title'
        oroneo_global_config_settings:
            title: 'synolia.oroneo.configuration_page.global_configuration.settings'
        oroneo_attribute_settings:
            title: 'synolia.oroneo.configuration_page.attribute.title'
        oroneo_global_config_localization:
            title: 'synolia.oroneo.configuration_page.global_configuration.localization.title'
        oroneo_mapping_settings:
            title: 'synolia.oroneo.configuration_page.mapping.settings'
        oroneo_config_category:
            title: 'synolia.oroneo.configuration_page.category.title'
        oroneo_config_attribute:
            title: 'synolia.oroneo.configuration_page.attribute.title'
        oroneo_config_option:
            title: 'synolia.oroneo.configuration_page.option.title'
        oroneo_config_product:
            title: 'synolia.oroneo.configuration_page.product.title'
        oroneo_config_category_settings:
            title: 'synolia.oroneo.configuration_page.category.settings'
        oroneo_config_attribute_settings:
            title: 'synolia.oroneo.configuration_page.attribute.settings'
        oroneo_config_option_settings:
            title: 'synolia.oroneo.configuration_page.option.settings'
        oroneo_config_product_settings:
            title: 'synolia.oroneo.configuration_page.product.settings'

    fields:
        # Global Configuration fields
        synolia_oroneo.delimiter:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.delimiter'
        synolia_oroneo.enclosure:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.enclosure'
        synolia_oroneo.attribute_file_max_size:
            data_type: integer
            type: integer
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.attribute_file_max_size.label'
                tooltip: 'synolia.oroneo.configuration_page.global_configuration.fields.attribute_file_max_size.tooltip'
        synolia_oroneo.attribute_image_width:
            data_type: integer
            type: integer
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.attribute_image_width.label'
                tooltip: 'synolia.oroneo.configuration_page.global_configuration.fields.attribute_image_width.tooltip'
        synolia_oroneo.attribute_image_height:
            data_type: integer
            type: integer
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.attribute_image_height.label'
                tooltip: 'synolia.oroneo.configuration_page.global_configuration.fields.attribute_image_height.tooltip'
        synolia_oroneo.localization_mapping:
            data_type: array
            type: synolia_Oroneo_localization_mapping
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.localization_mapping'
                resettable: false
        # Category Mapping
        synolia_oroneo.category_mapping:
            data_type: array
            type: synolia_Oroneo_category_mapping
            options:
                label: 'synolia.oroneo.configuration_page.category.mapping'
                resettable: false
        # Product Mapping & channel
        synolia_oroneo.product_mapping:
            data_type: array
            type: synolia_Oroneo_product_mapping
            options:
                label: 'synolia.oroneo.configuration_page.product.mapping'
                resettable: false
        synolia_oroneo.product_channel:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.product.channel'

    tree:
        system_configuration:
            oroneo:
                children:
                    oroneo_global_config:
                        children:
                            oroneo_global_config_settings:
                                children:
                                    oroneo_global_config_settings:
                                        children:
                                            - synolia_oroneo.delimiter
                                            - synolia_oroneo.enclosure
                                    oroneo_attribute_settings:
                                        children:
                                            - synolia_oroneo.attribute_file_max_size
                                            - synolia_oroneo.attribute_image_width
                                            - synolia_oroneo.attribute_image_height
                            oroneo_global_config_localization:
                                children:
                                    oroneo_global_config_localization:
                                        children:
                                            - synolia_oroneo.localization_mapping

                    oroneo_mapping_config:
                        children:
                            oroneo_config_category:
                                children:
                                    oroneo_config_category_settings:
                                        children:
                                            - synolia_oroneo.category_mapping
                            oroneo_config_product:
                                children:
                                    oroneo_config_product_settings:
                                        children:
                                            - synolia_oroneo.product_channel
                                            - synolia_oroneo.product_mapping
